# Generated by Django 6.0.1

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ScheduleSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('timezone', models.CharField(default='Europe/Madrid', help_text='IANA timezone for this hub (e.g. Europe/Madrid, America/New_York).', max_length=50, verbose_name='Timezone')),
                ('week_starts_on', models.IntegerField(default=1, help_text='1=Monday, 7=Sunday', verbose_name='Week Starts On')),
                ('slot_duration', models.IntegerField(default=30, help_text='Default time slot in minutes', verbose_name='Slot Duration')),
                ('auto_close_enabled', models.BooleanField(default=False, help_text='Automatically mark the business as closed after closing time.', verbose_name='Auto Close Enabled')),
            ],
            options={
                'verbose_name': 'Schedule Settings',
                'verbose_name_plural': 'Schedule Settings',
                'db_table': 'schedules_settings',
                'abstract': False,
                'unique_together': {('hub_id',)},
            },
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='0=Monday, 6=Sunday', verbose_name='Day of Week')),
                ('open_time', models.TimeField(default=datetime.time(9, 0), verbose_name='Open Time')),
                ('close_time', models.TimeField(default=datetime.time(18, 0), verbose_name='Close Time')),
                ('is_closed', models.BooleanField(default=False, help_text='If checked, the business is closed on this day.', verbose_name='Closed')),
                ('break_start', models.TimeField(blank=True, help_text='Start of midday break (optional).', null=True, verbose_name='Break Start')),
                ('break_end', models.TimeField(blank=True, help_text='End of midday break (optional).', null=True, verbose_name='Break End')),
            ],
            options={
                'verbose_name': 'Business Hours',
                'verbose_name_plural': 'Business Hours',
                'db_table': 'schedules_business_hours',
                'ordering': ['day_of_week'],
                'abstract': False,
                'unique_together': {('hub_id', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='SpecialDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('date', models.DateField(verbose_name='Date')),
                ('name', models.CharField(help_text='Name of the holiday or special day.', max_length=200, verbose_name='Name')),
                ('is_closed', models.BooleanField(default=True, help_text='If checked, the business is fully closed on this day.', verbose_name='Closed')),
                ('open_time', models.TimeField(blank=True, help_text='Special open time (only if not fully closed).', null=True, verbose_name='Open Time')),
                ('close_time', models.TimeField(blank=True, help_text='Special close time (only if not fully closed).', null=True, verbose_name='Close Time')),
                ('recurring_yearly', models.BooleanField(default=False, help_text='If checked, this special day recurs every year on the same date.', verbose_name='Recurring Yearly')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Special Day',
                'verbose_name_plural': 'Special Days',
                'db_table': 'schedules_special_day',
                'ordering': ['date'],
                'abstract': False,
                'unique_together': {('hub_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('reason', models.CharField(help_text='Reason for the schedule override.', max_length=200, verbose_name='Reason')),
                ('open_time', models.TimeField(blank=True, help_text='Override open time (leave empty to use regular hours).', null=True, verbose_name='Open Time')),
                ('close_time', models.TimeField(blank=True, help_text='Override close time (leave empty to use regular hours).', null=True, verbose_name='Close Time')),
                ('is_closed', models.BooleanField(default=False, help_text='If checked, the business is fully closed during this period.', verbose_name='Closed')),
            ],
            options={
                'verbose_name': 'Schedule Override',
                'verbose_name_plural': 'Schedule Overrides',
                'db_table': 'schedules_override',
                'ordering': ['-start_date'],
                'abstract': False,
            },
        ),
    ]
